version: '2'

services:
  application:
    image: debian
    volumes:
      - ./:/var/www/app
  hugo:
    image: dung13890/hugo-env
    restart: always
    volumes_from:
      - application
    tty: true
